package org.coreasm.testing;

/**
 * A module for the generation of the final coreasmc testing code.
 * A TestingHelperModule performs two tasks:
 * It replaces code in the string generated by the plugins code generation,
 * e.g. CompilerRuntime.BooleanElement is replaced with BooleanMock
 * And generates a code block for integration in the final testing class,
 * such as the BooleanMock class
 * @author Spellmaker
 *
 */
public interface TestingHelperModule {
	public String modifyCode(String code);
	public String getCodeBlock();
}
